# Generated by Django 3.2.18 on 2023-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Tips'), (2, 'Review')], default=0),
        ),
    ]
