# Generated by Django 3.2.18 on 2023-04-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Tips'), (2, 'Review'), (3, 'Locations')], default=0),
        ),
    ]
