# Generated by Django 3.2.18 on 2023-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Review'), (2, 'Destination')], default=0),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
