# Generated by Django 3.2.18 on 2023-04-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0009_auto_20230408_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Tips'), (2, 'Review'), (3, 'Destinations')], default=0),
        ),
    ]
