# Generated by Django 3.2.18 on 2023-04-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0012_auto_20230410_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catergory',
        ),
    ]
