# Generated by Django 3.2.18 on 2023-04-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0013_delete_catergory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
    ]
