# Generated by Django 3.2.18 on 2023-05-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0014_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
