# Generated by Django 3.2.18 on 2023-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0002_alter_list_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='planning',
            field=models.TextField(default='Add Planning Here'),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
