# Generated by Django 3.2.18 on 2023-04-20 12:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0003_auto_20230420_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='planning',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
