# Generated by Django 3.2.18 on 2023-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0006_alter_list_planning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='planning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
